Undefined array key 0 in Subject select input
PrestaShop/contactform pull request #73
Opened 2023-11-24 16:00 UTC by NicolasCador

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | When you send a message through the PO in BO, then you send a new message trough Customer Service in BO, there is an error in Subject select input.
| Type?         | bug fix
| BC breaks?    | yes
| Deprecations? | yes
| Fixed ticket? | Fixes PrestaShop/Prestashop#34672.
| How to test?  | Open an order in BO
Send a message to customer
Open Customer Service/Customer Service tab in BO
Send a new message concerning this PO
Open the customer e-mail, follow the link to answer
It opens the Contact us page
There isn't any error in the Subject select input

2023-11-25 08:53 UTC, mflasquin requested changes

2023-11-25 08:53 UTC, mflasquin commented on contactform.php
> +        if (isset($this->customer_thread['id_contact']) && $this->customer_thread['id_contact'] != 0) {
```suggestion
        if (isset($this->customer_thread['id_contact']) && $this->customer_thread['id_contact'] !== 0) {
```

2023-11-25 17:05 UTC, NicolasCador commented
hello @mflasquin,

ok, updated, thank you

2023-11-25 17:14 UTC, Hlavtox reviewed
Use `!empty(`, it will be the cleanest. :)

2023-11-25 17:20 UTC, NicolasCador commented
Hello @Hlavtox,

in fact we need to avoid 0 because array key 0 will be never defined. 

And finally, @mflasquin, I'm not sure we need to put !== because with that, if $this->customer_thread['id_contact'] is different than int type, $contacts[$this->customer_thread['id_contact']] will also give an error.
What do you think?

2023-11-25 18:45 UTC, Hlavtox commented
@NicolasCador Yes that is what empty will do. It will return true only if it's defined, not false, not null, not empty string, not zero. :-)

2023-11-25 23:40 UTC, SharakPL commented on contactform.php
> +        if (isset($this->customer_thread['id_contact']) && $this->customer_thread['id_contact'] !== 0) {
```suggestion
        if (!empty($this->customer_thread['id_contact'])) {
```
The same only shorter 😉

2023-11-26 18:09 UTC, NicolasCador commented
hello @Hlavtox,

ok, thank you very much, I didn't know for 0, I updated

2023-11-29 16:44 UTC, mflasquin approved these changes

2024-01-10 10:58 UTC, florine2623 approved these changes
Hello @NicolasCador ,

Tested your PR on PS `8.0.x`, `8.1.3` and `develop`.
It works as expected. No more error on the Subject !

It is QA ✅

2024-01-10 11:14 UTC, merged

2024-01-10 11:15 UTC, Hlavtox commented
Thanks everyone!